all:
	g++ test.cpp RPI.cpp Parsing.cpp Device.cpp Backend.cpp -Wall -g -o test  -I/usr/include/python2.7 -L/usr/lib/python2.7/config -lpython2.7 -lboost_system -lboost_thread -lusb-1.0 -lboost_python
